src/lists/urls.py
from django.contrib import admin
from django.urls import path
from lists import views

urlpatterns = [
    path('new', views.new_list, name="new_list"),
    path('<int:list_id>/', views.view_list, name="view_list"),
    path('<int:list_id>/add_item', views.add_item, name="add_item"),
]

src/superlists/urls.py
from django.contrib import admin
from django.urls import path, include
from lists import views as list_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', list_views.home_page, name="home"),
    path("lists/", include("lists.urls"))
]

src/lists/models.py
from django.db import models

class List(models.Model):
    pass

class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

src/lists/views.py
from django.shortcuts import render, redirect
from lists.models import Item, List

def home_page(request):
    return render(request, "home.html")

def view_list(request, list_id):
    our_list = List.objects.get(id=list_id)
    return render(request, "list.html", {"list": our_list})

def new_list(request):
    nulist = List.objects.create()
    Item.objects.create(text=request.POST["item_text"], list=nulist)
    return redirect(f"/lists/{nulist.id}/")

def add_item(request, list_id):
    ourlist = List.objects.get(id=list_id)
    Item.objects.create(text=request.POST["item_text"], list=ourlist)
    return redirect(f"/lists/{ourlist.id}/")

src/lists/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>To-Do lists</title>
  </head>
  <body>
    <h1>Start a new To-Do list</h1>
    <form action="/lists/new" method="post">
      <input
        id="id_new_item"
        name="item_text"
        placeholder="Enter a to-do item"
      />
      {% csrf_token %}
    </form>
  </body>
</html>

src/lists/templates/list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>To-Do lists</title>
  </head>
  <body>
    <h1>Your To-Do list</h1>
    <form action="/lists/{{ list.id }}/add_item" method="post">
      <input
        id="id_new_item"
        name="item_text"
        placeholder="Enter a to-do item"
      />
      {% csrf_token %}
    </form>
    <table id="id_list_table">
      {% for item in list.item_set.all %}
      <tr>
        <td>{{ forloop.counter}}: {{ item.text }}</td>
      </tr>
      {% endfor %}
    </table>
  </body>
</html>